@startuml

!$Business  = "Logica de Negocio"
!$Dispatch = "Despacho"

!$Persistence  = "Persistencia"
!$Hardware = "Hardware"
!$DB = "Database"

!$UseCases  = "Caso de Uso"
!$Entities  = "Entidades"

package $Dispatch {
        [ $Dispatch ]
}

package "$Persistence" {
        [ $Hardware ] 
        [ $DB ]
}

package "$Business" {
        package "$UseCases" {
                interface Login
                Login - [ $UseCases ]
        }

        package "$Entities" {
                interface Puerto

                Puerto - [ $Entities ]
        }

        
}


[ $Dispatch ] --( Login: "<<use>>"
[ $Hardware ] --( Puerto: "<<use>>"
@enduml
