@startuml(id=PACKAGE)

!$Business  = "Logica de Negocio"
!$UseCases  = "Caso de Uso"

package "$Business" {
        package "$UseCases" {
                class LoguearseComoOperador {
                        + login(id : string, pwd : Credencial)
                }
        }
}


