@startuml

!$Dispatch = "Despacho"
!$BussinesLogic  = "Logica de Negocio"
!$Presenter  = "Presentador"
!$Persistence  = "Persistencia"
!$Hardware = "Hardward"
!$DB = "Database"
!$UseCases  = "Caso de Uso"
!$Entities  = "Entidades"

package "$Dispatch" {}

package "$BussinesLogic" {
        package "$UseCases" {}
        package "$Entities" {}

        "$UseCases" ..> "$Entities"
}

package "$Presenter" {}
package "$Persistence" {
        package "$DB" {}
        package "$Hardware" {}
}

"$Dispatch" ...> "$BussinesLogic"
"$Presenter" ...> "$BussinesLogic"
"$Hardware" ..> "$Entities"

@enduml
