@startuml
":TestCase" -> ":SensorTemperatura": loging(usuario,password)

activate ":SensorTemperatura"
        ":SensorTemperatura" -> ":Usuario": verificar(usuario, password)
        activate ":Usuario"
                alt password == this->password && usuario == this->usuario
                        ":Usuario" --> ":SensorTemperatura": [ok]
                else  
                        ":Usuario" --> ":SensorTemperatura": [error]
                end
        deactivate ":Usuario"
        ":SensorTemperatura" --> ":TestCase": [error]

@enduml
