@startuml
":TestCase" -> ":SensorTemperatura": loging(usuario,password)

activate ":SensorTemperatura"
        loop cada usuario
                ":SensorTemperatura" -> ":Usuario": verificar(usuario, password)

                activate ":Usuario"
                        alt password == this->password && usuario == this->id
                                ":Usuario" --> ":SensorTemperatura": [ok = true]
                        else  
                                ":Usuario" --> ":SensorTemperatura": [error = false]
                        end
                deactivate ":Usuario"
        end
        
        /'
         ' ":SensorTemperatura" --> ":TestCase": [error = false]
         '/

@enduml
