@startuml
skinparam style strictuml

title Un usuario se loguea con sus credenciales correctas\n

":TestCase" -> ":SensorTemperatura": loging(usuario, password)
activate ":SensorTemperatura"
":SensorTemperatura" -> ":SensorTemperatura": verificacion(usuario, password)
":SensorTemperatura" --> ":TestCase": [ok]

@enduml
