@startuml
skinparam style strictuml

title Un usuario se loguea con sus credenciales correctas\n

":TestCase" -> "variableNombre :SensorTemperatura": loging(usuario, password)
activate "variableNombre :SensorTemperatura"
"variableNombre :SensorTemperatura" -> "variableNombre :SensorTemperatura": verificacion(usuario, password)
"variableNombre :SensorTemperatura" --> ":TestCase": [ok]

@enduml
