@startuml

/'
 ' skinparam classAttributeIconSize 0
 '/

class SensorTemperatura {
        - ID : uint
        - medición : double

        + SensorTemperatura()
        + Publicar()
        + verificar(id : string, pwd : Credencial) : bool
        - Sensar()
}

@enduml
