@startuml

!$Dispatch = "Despacho"

package "$Dispatch" {
        package CLI {
                class Cmd{
                        + login(id : string, pwd : Credencial)
                }
        }
}

@enduml
