@startuml

/'
' skinparam classAttributeIconSize 0
'/

class SensorTemperatura {
        - ID : uint
        - medición : double

        + SensorTemperatura()
        + Publicar() : Mensaje
        + login(id: string, pwd : Credencial) : bool
        + verificar(id : string, pwd : Credencial) : bool
        - Sensar()
}

@enduml
@startuml(id=PACKAGE)
!$Business  = "Logica de Negocio"
!$Entities  = "Entidades"

package "$Business" {
        package "$Entities" {
                class SensorTemperatura {
                        - ID : uint
                        - medición : double

                        + SensorTemperatura()
                        + Publicar() : Mensaje
                        + verificar(id : string, pwd : Credencial) : bool
                        + Medicion() : double
                        - Sensar()
                }
        }
}

@enduml
