@startuml

!$Dispatch = "Despacho"

package "$Dispatch" {
        package WebApp {
                class HtmlServer {
                        + login(id : string, pwd : Credencial)
                }
        }
}

@enduml
