@startuml

class Dispositivo {
        - ID : uint
        - puerto : &basic_ifstream

        + Dispositivo(ID : uint, ruta : std::string)
        + ~Dispositivo()
        # char* Sensar(char *buffer)
}


@enduml
@startuml(id=WITHOUT)

class Dispositivo {
        - ID : uint

        + Dispositivo(ID : uint, ruta : std::string)
        + ~Dispositivo()
        # char* Sensar(char *buffer)
}


@enduml
@startuml(id=PACKAGE)

!$Business  = "Logica de Negocio"
!$Persistence  = "Hardward"
!$UseCases  = "Caso de Uso"
!$Entities  = "Entidades"

package "$Business" {
        package "$Entities" {
                class Dispositivo {
                        - ID : uint

                        + Dispositivo(ID : uint, ruta : std::string)
                        + ~Dispositivo()
                        # char* Sensar(char *buffer)
                }
        }
}



@enduml
