@startuml

!include clase_usuario.plantuml!WITHOUT
!include clase_credencial.plantuml
!include clase_password.plantuml
!include clase_qr.plantuml

Usuario o- "\t\t1" Credencial: "\t\t - credencial"
Credencial <|-- Password
Credencial <|-- QR
@enduml
